# Comparativa de Normas Forenses Digitales

| Criterio / Pregunta | RFC 3227 | NIST SP 800-86 | Manual de buenas prácticas de ENFSI |
| :--- | :--- | :--- | :--- |
| **¿Qué entiende por identificar?** | Determinar en qué sistemas exactos se encuentra la evidencia tras un incidente, valorando qué datos son relevantes, válidos en un proceso legal y volátiles antes de iniciar la recogida de evidencias. *(Ap. 3.2)* | Capacidad de reconocer y rastrear todas las fuentes potenciales de datos. No se limita a lo obvio, abarcando elementos físicos visibles, medios extraíbles, dispositivos portátiles y fuentes remotas o lógicas. *(Ap. 3.1.1)* | Localización y reconocimiento de los elementos de prueba (*exhibits*) y las configuraciones de red y sistema en la escena. *(Ap. 9.2)* Incluye la previsión previa de evidencias volátiles o cifradas que podrían perderse si no se actúa rápido. *(Ap. 9.1)* |
| **¿Qué fuentes de evidencia menciona?** | • **Volátiles:** Registros y caché de la CPU, tablas de enrutamiento, caché ARP, tabla de procesos, memoria RAM, estadísticas del kernel y archivos temporales. *(Ap. 2.1)*<br>• **No volátiles:** Discos, logs remotos, datos de monitoreo, configuración física, topología de red y medios de archivo. *(Ap. 2.1)* | • **Sistemas y medios físicos:** Ordenadores, servidores, almacenamiento en red, USB, tarjetas SD, discos ópticos y magnéticos. *(Ap. 3.1.1)*<br>• **Dispositivos portátiles:** Móviles, PDAs, cámaras digitales, grabadoras, reproductores de audio. *(Ap. 3.1.1)*<br>• **Fuentes de red y externas:** Logs de red, registros de ISPs, equipos externos de teletrabajadores. *(Ap. 3.1.1)*<br>• **Fuentes proactivas:** Registros de auditoría del SO, servidores centrales de logs, backups, software de seguridad (antivirus/IDS) y keystroke logs. *(Ap. 3.1.1)* | • **Evidencia digital física y lógica:** Dispositivos conectados, capturas de pantalla, datos extraídos en tiempo real. *(Ap. 8.3, 9.2)*<br>• **Memoria y comunicaciones:** Memoria RAM dinámica, volúmenes cifrados activos y transmisiones por radiofrecuencia (RF) o infrarrojos. *(Ap. 8.3, 9.1)*<br>• **Evidencias físicas no digitales:** Muestras de ADN y huellas dactilares sobre los propios dispositivos. *(Ap. 8.3, 9.1)* |
| **¿Qué criterio propone para decidir qué se protege primero?** | **Criterio de volatilidad técnica:** Establece un orden estricto de recolección empezando siempre por los componentes cuyos datos se pierden más rápido (RAM, registros, cachés) y terminando en los menos volátiles (discos, respaldos) para evitar la pérdida irremediable. *(Ap. 2, 2.1)* | **Criterio de equilibrio (Valor vs. Coste e Impacto):** Sugiere valorar la fragilidad de la evidencia frente al impacto operativo y el coste de su recogida. *(Ap. 3.1, 3.1.3)* Ante fuentes inaccesibles, propone recurrir a fuentes de datos alternativas. *(Ap. 3.1.1)* | **Criterio de gestión de riesgos e integridad:** Prioriza el aislamiento físico y de red (evitar accesos remotos por RF e infrarrojos). *(Ap. 8.3)* Evalúa no apagar equipos si implica perder datos dinámicos y/o cifrados. *(Ap. 9.1, 9.2)* Coordina la actuación con otras especialidades (huellas, ADN) según el grado de destrucción. *(Ap. 8.3)* |

---

## Coincidencias y Diferencias

### ¿En qué coinciden?
- **Preservación e Integridad:** Coinciden principalmente en priorizar y proteger la evidencia original, minimizando lo máximo posible cualquier cambio o modificación de dicha evidencia.
- **Manejo de Equipos Encendidos:** Todas concuerdan en que hay que tener especial cuidado al apagar un equipo sin haber extraído o recogido antes la información volátil presente en la memoria RAM o en volúmenes cifrados activos.
- **Cadena de Custodia:** Coinciden en la obligación de llevar un registro detallado y fechado de cada paso realizado, las herramientas utilizadas y las personas involucradas, asegurando la trazabilidad de la cadena de custodia.

### ¿En qué se diferencian?
- **Enfoque de la guía:** La **RFC 3227** es una guía de actuación rápida enfocada prioritariamente en la volatilidad técnica. La **NIST SP 800-86** ofrece un enfoque más amplio de gestión de incidentes y fuentes externas/proactivas. La **ENFSI** se orienta hacia el entorno policial, procesal y de laboratorio.
- **Alcance del análisis:** La **RFC 3227** se centra principalmente en el equipo afectado y su red directa. La **NIST SP 800-86** extiende el seguimiento a entornos más complejos (ISPs, teletrabajo, logs proactivos). La **ENFSI** integra la evidencia digital con la física no digital (como huellas dactilares y muestras de ADN sobre los dispositivos).
